### ISSUE TITLE
Top left corner not getting proper curve when using SquircleComposeShape.

### ISSUE THREAD

**Issue by imnithish** [Juky-App/SquircleView#20]
While using SquircleComposeShape, the curve at the top left corner is way too much if the height of Composable is bit high. 

To Reproduce
  modifier = Modifier
            .fillMaxWidth()
            .height(700.dp)
            .graphicsLayer(
                shadowElevation = 8f,
                shape = SquircleComposeShape.SquircleComposeShape(cornerSmoothing = 80),
                clip = true
            )

Screenshot
https://imgur.com/a/ZIIAec5

**Comment by Nielssg** [comment]
This issue has been resolved in V0.6.1 which will be available shortly. Thanks for finding this issue! 😄
