### ISSUE TITLE
Squircle views have a ripple even though no click listener is set.

### ISSUE THREAD

**Issue by ThomasBakker** [Juky-App/SquircleView#5]
Squircle views have a ripple even though no click listener is set. Because of this the user of the app thinks he can click on something even though there is no click listener on it.

It would be nice if the ripple is only enabled when a click listener is set.

**Comment by Nielssg** [comment]
Great suggestion, will definitely look into it!

**Comment by Nielssg** [comment]
This issue will be solved in the upcoming 0.0.4 release, which I'll probably do this evening. Thanks for the suggestion, closing the issue
